### ISSUE TITLE
Automatically created tag name issues

### ISSUE THREAD

**Issue by jedrichards** [MoOx/github-release-from-changelog#8]
Hey

Firstly thanks for a great script :)

I noticed an inconsistency with the way `npm version` works though. If I do,

`npm version <new version>`

Then npm tags in the format `vX.Y.Z`. But this script decides on a tag name in the format `X.Y.Z`, without a `v`, which node-grizzly will go ahead and create if it doesn't exist. So then I get a pair of tags in my repo releases, `vX.Y.Z` and `X.Y.Z`.

I found this surprising because in the readme it says,

> You need: a git tag with the corresponding version

So since I already had a tag in the npm format I was expecting it to be picked up and used. Or alternatively, if a tag wasn't present in the format this script was expecting then I'd expect it to error out, rather than create that tag.

Would you be open to a PR that does some or all of the below?

a) Aligns this script with the tag name format you get from npm when using `npm version`
b) Adds an option so that the tag name format can be specified by the user, e.g. `v%s` so they can use the `v` in front style if they want to
c) Exits with an error if the tag the script is expecting to use isn't present in the repo

Thanks!

**Comment by MoOx** [comment]
- This script is mainly used in https://github.com/MoOx/npmpub which does not use "npm version".
- I was not aware that grizzly will create a tag, so this behavior is not intentional :/

a) this will be a breaking change, so not really
b) that can be an option
c) I think I have a better idea:

What about getting the tag name by matching x.y.x from the "git tag" result? This way if people use vX.Y.Z or X.Y.Z we will found the tag automatically. What do you think?
Mathing something like /^(v?)X.Y.Z$/gm

See http://refiddle.com/refiddles/56b8b15075622d5a70020000

**Comment by jedrichards** [comment]
Yeah, cool, I like your better idea :)

So look in `git tag` and error if it can't be matched?

**Comment by MoOx** [comment]
Yeah !

**Comment by jedrichards** [comment]
:+1: Will try to get round to a PR soon.

**Comment by MoOx** [comment]
Closed by 42f43fadc03b116778a8ac9e8e1fd9712e5c808b
